spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/taotao?useSSL=false
    username: root
    password: root

  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates
    suffix: .html

  redis:
    host: 127.0.0.1
    port: 6379
    maxTotal: 30

logging:
  config: classpath:logback-spring.xml
  level:
    root: info

mybatis:
  type-aliases-package: cn.hzr0523.entity
  mapper-locations: classpath:mapper/*.xml

USER_SESSION_KEY: REDIS_USER_SESSION
SSO_SESSION_EXPIRE: 30

